# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo ::set-output name=repo-name::$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Checkout Current Repo
      uses: actions/checkout@v3
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: adafruit/actions-ci-circuitpython-libs
        path: actions-ci
    - name: Install dependencies
      # (e.g. - apt-get: gettext, etc; pip: circuitpython-build-tools, requirements.txt; etc.)
      run: source actions-ci/install.sh
    - name: Pip install Sphinx deps, pre-commit
      run: |
        pip install pre-commit twine -r examples/requirements.txt -r docs/requirements.txt
        sudo apt-get install graphviz
    - name: Build wheel
      run: pip wheel -w dist --no-deps .
    - name: check dist
      run: twine check dist/*
    - name: Setup problem matchers
      uses: adafruit/circuitpython-action-library-ci-problem-matchers@v1
    - name: Pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --package_folder_prefix "" --library_location .
    - name: Archive bundles
      uses: actions/upload-artifact@v3
      with:
        name: bundles
        path: ${{ github.workspace }}/bundles/
    - name: Archive wheel
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: ${{ github.workspace }}/dist/
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
    - name: Archive docs
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ${{ github.workspace }}/docs/_build/html
